<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\teapot.obj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\teapot.obj" />
    <EmbeddedResource Include="Resources\cube.obj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET" Version="2.20.0" />
    <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.20.0" />
  </ItemGroup>

</Project>
