<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\asteroid.obj" />
    <None Remove="Resources\skybox.png" />
    <None Remove="Resources\skyboxstar.jpg" />
    <None Remove="Resources\spaceship.obj" />
    <None Remove="Resources\teapot.obj" />
    <None Remove="Shaders\FragmentShader.frag" />
    <None Remove="Shaders\VertexShader.vert" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\asteroid.obj" />
    <EmbeddedResource Include="Resources\skybox.png" />
    <EmbeddedResource Include="Resources\skyboxstar.jpg" />
    <EmbeddedResource Include="Resources\spaceship.obj" />
    <EmbeddedResource Include="Resources\teapot.obj" />
    <EmbeddedResource Include="Shaders\FragmentShader.frag" />
    <EmbeddedResource Include="Shaders\VertexShader.vert" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET" Version="2.20.0" />
    <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.20.0" />
    <PackageReference Include="StbImageSharp" Version="2.27.14" />
  </ItemGroup>

</Project>
